# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160204_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='alignment',
        ),
        migrations.RemoveField(
            model_name='character',
            name='charisma',
        ),
        migrations.RemoveField(
            model_name='character',
            name='constitution',
        ),
        migrations.RemoveField(
            model_name='character',
            name='dexterity',
        ),
        migrations.RemoveField(
            model_name='character',
            name='exp_points',
        ),
        migrations.RemoveField(
            model_name='character',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='character',
            name='player',
        ),
        migrations.RemoveField(
            model_name='character',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='character',
            name='wisdom',
        ),
        migrations.AddField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Femail'), ('A', 'Asexual'), ('N', 'Not Defined')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(choices=[('Acolyte', 'Acolyte'), ('Criminal', 'Criminal'), ('Charlatan', 'Charlatan'), ('Entertainer', 'Entertainer'), ('Folk Hero', 'Folk Hero'), ('Guild Artisan', 'Guild Artisan'), ('Hermit', 'Hermit'), ('Noble', 'Noble'), ('None', 'None'), ('Other', 'Other'), ('Outlander', 'Outlander'), ('Sage', 'Sage'), ('Sailor', 'Sailor'), ('Soldier', 'Soldier'), ('Urchin', 'Urchin')], default='None', max_length=15),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.CharField(choices=[('Cleric', 'Cleric'), ('Fighter', 'Fighter'), ('Rogue', 'Rogue'), ('Wizard', 'Wizard'), ('Barbarian', 'Barbarian'), ('Bard', 'Bard'), ('Druid', 'Druid'), ('Monk', 'Monk'), ('Paladin', 'Paladin'), ('Ranger', 'Ranger'), ('Sorcerer', 'Sorcerer'), ('Warlock', 'Warlock')], default='Fighter', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.CharField(choices=[('Dragonborn', 'Dragonborn'), ('Drow', 'Drow'), ('Dwarf', 'Dwarf'), ('Elf', 'Elf'), ('Gnome', 'Gnome'), ('Half-elf', 'Half-elf'), ('Half-orc', 'Half-orc'), ('Halfling-Hobbit', 'Halfling-Hobbit'), ('Human', 'Human'), ('Tiefling', 'Tiefling')], default='Human', max_length=15),
        ),
    ]
