# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20160207_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Bond',
                'verbose_name_plural': 'Bonds',
            },
        ),
        migrations.CreateModel(
            name='Flaws',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flaw', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Flaw',
                'verbose_name_plural': 'Flaws',
            },
        ),
        migrations.CreateModel(
            name='Ideals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Ideal',
                'verbose_name_plural': 'Ideals',
            },
        ),
        migrations.CreateModel(
            name='PersonalityTraits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'PersonalityTrait',
                'verbose_name_plural': 'PersonalityTraits',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='charisma',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='character',
            name='hp_max',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='player_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='speed',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='temp_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Asexual'), ('N', 'Not Defined')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='personalitytraits',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Character'),
        ),
        migrations.AddField(
            model_name='ideals',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Character'),
        ),
        migrations.AddField(
            model_name='flaws',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Character'),
        ),
        migrations.AddField(
            model_name='bonds',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Character'),
        ),
    ]
