# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20160207_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonds',
            name='character',
        ),
        migrations.RemoveField(
            model_name='flaws',
            name='character',
        ),
        migrations.RemoveField(
            model_name='ideals',
            name='character',
        ),
        migrations.RemoveField(
            model_name='personalitytrait',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='bonds',
            field=models.ManyToManyField(to='app.Bonds'),
        ),
        migrations.AddField(
            model_name='character',
            name='cha_advantage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='cha_expertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='cha_proficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='con_advantage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='con_expertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='con_proficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='dex_advantage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='dex_expertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='dex_proficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='diety',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='distinguishing_marks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='domain',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='downtime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='eyes',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='flaws',
            field=models.ManyToManyField(to='app.Flaws'),
        ),
        migrations.AddField(
            model_name='character',
            name='hair',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='honor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='ideals',
            field=models.ManyToManyField(to='app.Ideals'),
        ),
        migrations.AddField(
            model_name='character',
            name='int_advantage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='int_expertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='int_proficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='lifestyle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='piety',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='size',
            field=models.CharField(default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='skin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='str_advantage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='str_expertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='str_proficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='traits',
            field=models.ManyToManyField(to='app.PersonalityTrait'),
        ),
        migrations.AddField(
            model_name='character',
            name='vision',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='weight',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='character',
            name='wis_advantage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='wis_expertise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='wis_proficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='xp_next_level',
            field=models.IntegerField(default=0),
        ),
    ]
