# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160212_1908'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bonds',
            new_name='Bond',
        ),
        migrations.RenameModel(
            old_name='Flaws',
            new_name='Flaw',
        ),
        migrations.RenameModel(
            old_name='Ideals',
            new_name='Ideal',
        ),
    ]
