# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-13 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20160212_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Backgrounds',
                'verbose_name': 'Background',
            },
        ),
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_class', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Character Classes',
                'verbose_name': 'Character Class',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name_plural': 'Genders',
                'verbose_name': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Races',
                'verbose_name': 'Race',
            },
        ),
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.CharClass'),
        ),
        migrations.AlterField(
            model_name='character',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Gender'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Race'),
        ),
    ]
